### ISSUE TITLE
ScreenCaptureUtil.screenCapture 返回 500

### ISSUE THREAD

**Issue by zisheng-ai** [LewinJun/react-native-lewin-screen-capture#2]
![image](https://user-images.githubusercontent.com/13204332/59258437-8f4b2780-8c6a-11e9-9697-76f4a736349d.png)

**Comment by LewinJun** [comment]
Example的呢？  500 一般是图片文件不存在

**Comment by LewinJun** [comment]
详细的异常log信息有没有

**Comment by LewinJun** [comment]
有异常我会打印出来的  e.printStackTrace();

**Comment by songxiaoliang** [comment]
@LewinJun 加入我对微信交流群吧，帮助他们一下

**Comment by LewinJun** [comment]
没微信群

**Comment by songxiaoliang** [comment]
@LewinJun 加我mir_song，我拉你

**Comment by zisheng-ai** [comment]
放弃这个插件了，已经很详细了，你给的错误就这么多

**Comment by callcter** [comment]
android还是ios
你给的错误信息太少了 @youngjuning

**Comment by zisheng-ai** [comment]
android，没有报错，只返回了500

**Comment by callcter** [comment]
单纯截屏的话我推荐用react-native-view-shot

**Comment by LewinJun** [comment]
[微信群](https://dist-client.oss-cn-shanghai.aliyuncs.com/WechatIMG451.png )  加入群聊及时通知

**Comment by zisheng-ai** [comment]
+1

**Comment by jianglianEin** [comment]
返回的500，logcat报错
![image](https://user-images.githubusercontent.com/26169986/120723596-a264fb00-c504-11eb-8ae6-061d72d7e96c.png)

**Comment by zisheng-ai** [comment]
@jianglianEin https://github.com/sishuguojixuefu/react-native-screenshot 可以用这个，我之前封装了支持 ios android 的
