### ISSUE TITLE
screenshot as background service

### ISSUE THREAD

**Issue by sankar2389** [LewinJun/react-native-lewin-screen-capture#6]
Hi I tried your screen capture code. I can able to take screenshot of the app screen, but couldn't able to take screenshot in background mode. I created a Android Native App which can able to take screenshot as background service (https://github.com/sankar2389/ScreenshotNative-Media-Projection) but couldn't able to write exact react native bridge. Can you pls guide me?

**Comment by LewinJun** [comment]
How can I help you？

**Comment by LewinJun** [comment]
> Hi I tried your screen capture code. I can able to take screenshot of the app screen, but couldn't able to take screenshot in background mode. I created a Android Native App which can able to take screenshot as background service (https://github.com/sankar2389/ScreenshotNative-Media-Projection) but couldn't able to write exact react native bridge. Can you pls guide me?

I help you add your Android project to my project and provide a separate method to execute your code, right？

**Comment by sankar2389** [comment]
Hi @LewinJun I finished the binding https://github.com/sankar2389/capture_screenshot 
But I could not do this in native iOS. can you please guide or refer me some steps to work this on iOS?

**Comment by LewinJun** [comment]
> Hi @LewinJun I finished the binding https://github.com/sankar2389/capture_screenshot
> But I could not do this in native iOS. can you please guide or refer me some steps to work this on iOS?

You can refer to my component and call my component method on IOS，example: Platorm.OS === 'android',  use your method on android, Platorm.OS === 'ios' use react-native-lewin-screen-capture

Maybe,  I help your project  add react-native-lewin-screen-capture for package.json and add correlation method in App.js

**Comment by sankar2389** [comment]
But react-native-lewin-screen-capture can only capture the screenshot of our app only. My intention is to take all other applications or the current screen shown in the display (even our goes background) needed to capture.

**Comment by LewinJun** [comment]
> But react-native-lewin-screen-capture can only capture the screenshot of our app only. My intention is to take all other applications or the current screen shown in the display (even our goes background) needed to capture.

This is a method component, you look README.md
